<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('sprintbacklog-escolher-projeto') ?>">Escolher projeto</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('sprintbacklog', array('cod_projeto' => $this->cod_projeto)) ?>">Sprint Backlog</a></li>
        <li class="breadcrumb-item active">Cadastrar Sprint Backlog</li>
    </ol>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <spant> Sprint Backlog cadastrada com sucesso!</spant>
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('sprintbacklog', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />

<div class="content">

    <?php
    $formSprintBacklog = $this->form_sprint_backlog;
    $formSprintBacklog->prepare();
    echo $this->form()->openTag($formSprintBacklog);
    ?>

    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('nome_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('descricao_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('tempo_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_participante')); ?>
    </div>

    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_status')); ?>
    </div>

    <div class="form-group">
        <input type="hidden" name="cod_projeto" id="cod_projeto" value="<?= $this->cod_projeto ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('sprintbacklog', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>
    function verificarMinTempo(tempo){
        var tempo = tempo;
        alert(tempo);
    }

    $('#tempo_sprint_backlog').mask('99:99');
    $(document).ready(function () {
//        $('#telefone_sprint').mask('(99) 99999-9999');

        $('#form_sprint_backlog').validate({
            // Define as regras
            rules: {
                cod_product_backlog: {
                    required: true,
                },
                nome_sprint_backlog: {
                    required: true,
                },
                tempo_sprint_backlog: {
                    required: true,
                },
                cod_participante: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                cod_product_backlog: {
                    required: "Campo Product Backlog não pode ser vazio!",
                },
                nome_sprint_backlog: {
                    required: "Campo Nome da Sprint Backlog não pode ser vazio!",
                },
                tempo_sprint_backlog: {
                    required: "Campo Tempo de duração  não pode ser vazio!",
                },
                cod_participante: {
                    required: "Campo Atribuido para, não pode ser vazio!",
                },
            }
        });
    });
</script>