<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$this->url('inicio')?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('sprintbacklog-escolher-projeto')?>">Escolher projeto</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('sprintbacklog',array('cod_projeto'=>$this->cod_projeto))?>">Sprint Backlog</a></li>
        <li class="breadcrumb-item active">Excluir Sprint Backlog</li>
    </ol>
</div>
<?php
if (!isset($_POST['cod_sprint_backlog'])) {
    ?>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"  aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Você está prestes a excluir uma Sprint Backlog!</b><br /><br />
                    Você tem certeza que deseja excluir?
                </div>

                <div class="modal-footer">
                    <button type="button" name="excluir" id="excluir" class="btn btn-primary" onclick="excluir();">Sim</button>
                    <a href="<?=$this->url('sprintbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-warning">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>

    <?php
}

if (isset($this->retorno) && $this->retorno == true) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    Sprint Backlog excluída com sucesso!
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('sprintbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />

<div class="content">

    <?php
    $formSprintBacklog = $this->form_sprint_backlog;
    $formSprintBacklog->prepare();
    echo $this->form()->openTag($formSprintBacklog);
    ?>

    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('nome_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('descricao_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('tempo_sprint_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_participante')); ?>
    </div>

    <div class="form-group">
        <?= $this->formRow($formSprintBacklog->get('cod_status')); ?>
    </div>

    <div class="form-group">
        <input type="hidden" name="cod_projeto" id="cod_projeto" value="<?= $this->cod_projeto ?>">
        <a href="<?=$this->url('sprintbacklog-excluir',array('cod_projeto'=>$this->cod_projeto,'cod_sprint_backlog'=>$this->cod_sprint_backlog)) ?>" class="btn btn-danger" ><span class="glyphicon glyphicon-trash"></span> Excluir</a>
        <a href="<?= $this->url('sprintbacklog', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>
bloquerCampos();
    function excluir() {
        var formulario = document.getElementById('form_sprint_backlog');
        formulario.submit();

        return true;
    }

    function bloquerCampos() {
        var nomeSprintBacklog = document.getElementById('nome_sprint_backlog');
        var descricaoSprintBacklog = document.getElementById('descricao_sprint_backlog');
        var tempoSprintBacklog = document.getElementById('tempo_sprint_backlog');
        var codStatus = document.getElementById('cod_status');
        var codProductBacklog = document.getElementById('cod_product_backlog');
        var codParticipante = document.getElementById('cod_participante');

        nomeSprintBacklog.setAttribute('disabled', 'disabled');
        descricaoSprintBacklog.setAttribute('disabled', 'disabled');
        tempoSprintBacklog.setAttribute('disabled', 'disabled');
        codStatus.setAttribute('disabled', 'disabled');
        codProductBacklog.setAttribute('disabled', 'disabled');
        codParticipante.setAttribute('disabled', 'disabled');
    }
</script>