
<tr>
    <td><?=$this->codSprintBacklog?></td>
    <td><?=$this->nomeSprintBacklog?></td>
    <td><?=$this->descricaoSprintBacklog?></td>
    <td><?= $this->tempoSprintBacklog?> Horas</td>
    <td><?=$this->descricaoStatus?></td>
    <td><?=$this->nomeParticipante?></td>
    <td>
        <a href="<?=$this->url('sprintbacklog-editar',array('cod_projeto'=>$this->codProjeto,'cod_sprint_backlog'=>$this->codSprintBacklog)) ?>" class="btn btn-primary" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="<?=$this->url('sprintbacklog-excluir',array('cod_projeto'=>$this->codProjeto,'cod_sprint_backlog'=>$this->codSprintBacklog)) ?>" class="btn btn-danger" title="Excluir"><span class="glyphicon glyphicon-trash"></span></a>
    </td>    
</tr>
