<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('sprint', array('cod_projeto' => $this->cod_projeto)) ?>">Sprint</a></li>
        <li class="breadcrumb-item active">Cadastrar Product Backlog</li>
    </ol>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <spant> Sprint cadastrada com sucesso!</spant>
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('projeto', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formSprint = $this->form_sprint;
    $formSprint->prepare();
    echo $this->form()->openTag($formSprint);
    ?>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('nome_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('descricao_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('tempo_sprint')); ?>
    </div>

    <div class="form-group">
        <?= $this->formRow($formSprint->get('cod_status')); ?>
    </div>

    <div class="form-group">
        <input type="hidden" name="cod_projeto" id="cod_projeto" value="<?= $this->cod_projeto ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('sprint', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>

    $(document).ready(function () {
        $('#cpf_sprint').mask('999.999.999-99');
        $('#telefone_sprint').mask('(99) 99999-9999');

        $('#form_sprint').validate({
            // Define as regras
            rules: {
                nome_sprint: {
                    required: true,
                },
                tempo_sprint: {
                    required: true,
                },
                cod_projeto: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_sprint: {
                    required: "Campo Nome da Sprint não pode ser vazio!",
                },
                tempo_sprint: {
                    required: "Campo Tempo de duração  não pode ser vazio!",
                },
                cod_projeto: {
                    required: "Campo Projeto não pode ser vazio!",
                },
            }
        });
    });
</script>