<div class="box-header with-border">
    <h3 class="box-title">Cadastrar Sprint</h3>
</div>
<?php

if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Sprint cadastrada com sucesso!</b><br /><br />
                    Você deseja fazer alguma alteração?
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('sprint-editar', array('action' => 'editar', 'cod_sprint' => $this->ultimoSprint)) ?>" class="btn btn-default">Sim</a>
                    <a href="/sprint" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formSprint = $this->form_sprint;
    $formSprint->prepare();
    echo $this->form()->openTag($formSprint);
    ?>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('cod_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('nome_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('descricao_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('tempo_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('cod_status')); ?>
    </div>
    
    <div class="form-group">
        <?= $this->formRow($formSprint->get('botao_salvar')); ?>
        <a href="<?= $this->url('sprint') ?>" class="btn btn-danger" >Cancelar</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>

    $(document).ready(function () {
        $('#cpf_sprint').mask('999.999.999-99');
        $('#telefone_sprint').mask('(99) 99999-9999');

        $('#form_sprint').validate({
            // Define as regras
            rules: {
                nome_sprint: {
                    required: true,
                },
                
                tempo_sprint: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_sprint: {
                    required: "Campo Nome da Sprint não pode ser vazio!",
                },

                tempo_sprint: {
                    required: "Campo Tempo de duração  não pode ser vazio!",
                },
            }
        });
    });
</script>