<div class="box-header with-border">
    <h3 class="box-title">Editar sprint</h3>
</div>
<?php
//var_dump($this->retorno);
if (isset($_POST['botao_salvar']) && ($this->retorno == 1)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Sprint alterada com sucesso!</b><br /><br />
                    Você deseja fazer mais alguma alteração?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Sim</button>
                    <a href="/sprint" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>

<hr />
<div class="content">
   <?php
    $formSprint = $this->form_sprint;
    $formSprint->prepare();
    echo $this->form()->openTag($formSprint);
    ?>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('cod_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('nome_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('descricao_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('tempo_sprint')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSprint->get('cod_status')); ?>
    </div>
    
    <div class="form-group">
        <?= $this->formRow($formSprint->get('botao_salvar')); ?>
        <a href="<?= $this->url('sprint') ?>" class="btn btn-danger" >Cancelar</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>  
</div>

<script>
    

    $(document).ready(function () {
        $('#cpf_sprint').mask('999.999.999-99');
        $('#telefone_sprint').mask('(99) 99999-9999');

        $('#form_sprint').validate({
            // Define as regras
            rules: {
                nome_sprint: {
                    required: true,
                },
                cpf_sprint: {
                    required: true,
                    minlength: 14,
                },
                email_sprint: {
                    required: true,
                    email: true,
                },
                tipo_sprint: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_sprint: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_sprint: {
                    required: "Campo CPF não pode ser vazio!",
                    minlength: "O Campo CPF deve ter 11 números!"

                },
                email_sprint: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                tipo_sprint: {
                    required: "Campo Tipo de Sprint não pode ser vazio!",
                },
            }
        });
    });
</script>