<div class="box-header with-border">
    <h3 class="box-title">Sprint</h3>
</div>

<hr />
<a href="<?php echo $this->url('sprint-cadastrar', array('action' => 'cadastrar', 'cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-success">Nova Sprint</a>
<a class="btn btn-primary" id="editar-btn" disabled >Editar</a>
<a class="btn btn-danger" id="excluir-btn" disabled >Excluir</a>
<p></p>
<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Sprint</th>
            <th>Código</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Tempo de Duração</th>
            <th>Status</th>

        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('partial_loop_listar.phtml', $this->partial_loop_listar) ?>  
    </tbody>
</table>
