<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/inicio">Inicio</a></li>
        <li class="breadcrumb-item"><a href="/projeto">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto-gerenciar',array('cod_projeto'=>$this->cod_projeto))?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item active">Sprint</li>
    </ol>
</div>
<hr />
<a href="<?php echo $this->url('sprint-cadastrar', array('action' => 'cadastrar', 'cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-success"><span class="glyphicon glyphicon-file"></span> Nova Sprint</a>
<p></p>
<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Tempo de Duração</th>
            <th>Status</th>
            <th>Editar | Excluir</th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('partial_loop_listar.phtml', $this->partial_loop_listar) ?>  
    </tbody>
</table>
