<div class="box-header with-border">
    <h3 class="box-title">Participante por Projeto</h3>
</div>

<hr />

Participante: Fulano<br />
Tipo do Participante: Teste

<hr/>
<?php
if (isset($_POST['botao_salvar'])) {
    var_dump($_POST);
}
?>
<form name="participante_projeto" id="participante_projeto" method="post">
    <div class="form-group">
        <?= $this->partialLoop('partial_loop_projetos.phtml', $this->partial_loop_projetos) ?> 
    </div>
    <div class="form-group">
        <input type="submit" id="botao_salvar" class="btn btn-primary" name="botao_salvar" value="Salvar" >
        <a href="<?= $this->url('participanteprojeto') ?>" class="btn btn-warning" >Cancelar</a>
    </div>

</form>
