<div class="box-header with-border">
    <h3 class="box-title">Participante por Projeto</h3>
</div>

<hr />
<p>Escolha um participante para incluí-lo em um ou mais projetos: 
    <select  name="participante" id="participante" class="form-control" onchange="escolherParticipante(this);">
        <option>Selecione...</option>
        <?= $this->partialLoop('partial_loop_participantes.phtml', $this->partial_loop_participantes) ?>  
    </select>
</p>
<p>
    <a  id="add-btn"class="btn btn-success"  disabled>Incluir em Projeto</a>
</p>

<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Projeto</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('partial_loop_participante_projetos.phtml', $this->partial_loop_participante_projetos) ?>  

    </tbody>
</table>

<script>
    function escolherParticipante(codParticipante) {
        var codParticipante = codParticipante.value;
        var add = document.getElementById('add-btn');

        add.removeAttribute('disabled');

        add.setAttribute('href', 'participanteprojeto-add/' + codParticipante);
        
    }
    
    function mostrarProjetos(){
       var ajax = new XMLHttpRequest();
       ajax.onreadystatechange = function () {
       if (ajax.readyState == 4)
       {
           if (ajax.status == 200) {
               if (ajax.responseText) {
             //alert(ajax.responseText);
                       document.getElementById('t53_garant').value = ajax.responseText;
               }
                   else{
               alert("error");
                    }

           } else {
              // alert(ajax.statusText);
           }
       }
   }
       dados = 'method=carregaGarantia&t53_codbem='+t53_codbem;
//alert(dados);
       ajax.open("POST", "lt_lote_empenhoRCP.php", true);
       ajax.setRequestHeader('Content-Type','application/x-www-form-urlencoded;charset=iso-8859-1');
       ajax.send(dados);
   }

</script>
