<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>">Gerenciar projeto: <?= $this->nomeProjeto ?></a></li>
        <li class="breadcrumb-item active">Participante no Projeto</li>
    </ol>
</div>

<hr />
<?php // var_dump($this->participante_por_projeto);?>
<?php echo $this->codParticipante ?>
<form method="post">
    <table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" role="grid" aria-describedby="data_table_info" style="width: 100%;" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th><input type="checkbox" name="todos" > Todos </th>
                <td>Participante</td>
                <td>Tipo Participante</td>
                <td>CPF Participante</td>
                <td>Email Participante</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->participante_por_projeto as $participante) { ?>

                <?php //if ( (isset($participante->codProjeto) && $participante->codProjeto == $this->cod_projeto) || ($participante->codProjeto == null)  ) { ?> 
                <tr>
                    <td><input type="checkbox" name="participante[]" value="<?= $participante->codParticipantePt ?>"
                               <?php if ($participante->codParticipante != null /*&& $participante->codProjeto == $this->cod_projeto*/) { ?> checked="checked" <?php } ?>>  </td>
                    <td><?= $participante->nomeParticipante ?></td>
                    <td><?= $participante->tipoParticipante ?></td>
                    <td><?= $participante->cpfParticipante ?></td>
                    <td><?= $participante->emailParticipante ?></td>


                </tr>
                <?php
//            }
            }
            ?>

        </tbody>
    </table>
    <div class="form-group">
        <input type="hidden" name="cod_sprint" id="cod_sprint" value="<?= $this->cod_sprint ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
</form>

<script>
//    function deleteLinha() {
//        document.getElementById('deleteLinha').deleteRow();
//    }
</script>




