<div class="box-header with-border">
    <h3 class="box-title">Cadastrar Product Backlog</h3>
</div>
<?php

if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Participante cadastrado com sucesso!</b><br /><br />
                    Você deseja fazer alguma alteração?
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('participante-editar', array('action' => 'editar', 'cod_participante' => $this->ultimoParticipante)) ?>" class="btn btn-default">Sim</a>
                    <a href="/participante" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formProductBacklog = $this->form_productbacklog;
    $formProductBacklog->prepare();
    echo $this->form()->openTag($formProductBacklog);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('nome_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('descricao_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('prioridade_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('botao_salvar')); ?>
        <a href="/projeto/<?= $this->cod_projeto ?>/productbacklog" class="btn btn-danger" >Cancelar</a>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>

//    $(document).ready(function () {
//        $('#cpf_participante').mask('999.999.999-99');
//        $('#telefone_participante').mask('(99) 99999-9999');
//
//        $('#form_participante').validate({
//            // Define as regras
//            rules: {
//                nome_participante: {
//                    required: true,
//                },
//                cpf_participante: {
//                    required: true,
//                    minlength: 14,
//                },
//                email_participante: {
//                    required: true,
//                    email: true,
//                },
//                cod_tipo_participante: {
//                    required: true,
//                },
//            },
//            // Define as mensagens de erro para cada regra
//            messages: {
//                nome_participante: {
//                    required: "Campo Nome não pode ser vazio!",
//                },
//                cpf_participante: {
//                    required: "Campo CPF não pode ser vazio!",
//                    minlength: "O Campo CPF deve ter 11 números!"
//
//                },
//                email_participante: {
//                    required: "Campo E-mail não pode ser vazio!",
//                    email: "Formato email dever ter (@ e .com)!",
//                },
//                cod_tipo_participante: {
//                    required: "Campo Tipo de Participante não pode ser vazio!",
//                },
//            }
//        });
//    });
</script>