<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$this->url('inicio')?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto')?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto-gerenciar',array('cod_projeto'=>$this->cod_projeto))?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>">Product Backlog</a></li>
        <li class="breadcrumb-item active">Editar Product Backlog</li>
    </ol>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <span>Product Backlog alterado com sucesso!</span>
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formProductBacklog = $this->form_productbacklog;
    $formProductBacklog->prepare();
    echo $this->form()->openTag($formProductBacklog);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('nome_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('descricao_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('prioridade_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <input type="hidden" name="cod_projeto" id="cod_projeto" value="<?= $this->cod_projeto ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>

//    $(document).ready(function () {
//        $('#cpf_participante').mask('999.999.999-99');
//        $('#telefone_participante').mask('(99) 99999-9999');
//
//        $('#form_participante').validate({
//            // Define as regras
//            rules: {
//                nome_participante: {
//                    required: true,
//                },
//                cpf_participante: {
//                    required: true,
//                    minlength: 14,
//                },
//                email_participante: {
//                    required: true,
//                    email: true,
//                },
//                cod_tipo_participante: {
//                    required: true,
//                },
//            },
//            // Define as mensagens de erro para cada regra
//            messages: {
//                nome_participante: {
//                    required: "Campo Nome não pode ser vazio!",
//                },
//                cpf_participante: {
//                    required: "Campo CPF não pode ser vazio!",
//                    minlength: "O Campo CPF deve ter 11 números!"
//
//                },
//                email_participante: {
//                    required: "Campo E-mail não pode ser vazio!",
//                    email: "Formato email dever ter (@ e .com)!",
//                },
//                cod_tipo_participante: {
//                    required: "Campo Tipo de Participante não pode ser vazio!",
//                },
//            }
//        });
//    });
</script>