<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$this->url('inicio')?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto')?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto-gerenciar',array('cod_projeto'=>$this->cod_projeto))?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>">Product Backlog</a></li>
        <li class="breadcrumb-item active">Excluir Product Backlog</li>
    </ol>
</div>
<?php
if (!isset($_POST['cod_product_backlog'])) {
    ?>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"  aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Você está prestes a excluir um Product Backlog!</b><br /><br />
                    Você tem certeza que deseja excluir?
                </div>

                <div class="modal-footer">
                    <button type="button" name="excluir" id="excluir" class="btn btn-primary" onclick="excluir();">Sim</button>
                    <a href="<?=$this->url('sprint',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-warning">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>

    <?php
}
if (isset($_POST['cod_product_backlog'])) {
    ?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <span>Product Backlog excluido com sucesso!</span>
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formProductBacklog = $this->form_productbacklog;
    $formProductBacklog->prepare();
    echo $this->form()->openTag($formProductBacklog);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('nome_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('descricao_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('prioridade_product_backlog')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProductBacklog->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <input type="hidden" name="cod_projeto" id="cod_projeto" value="<?= $this->cod_projeto ?>">
        <button type="submit" name="botao_excluir" id="botao_salvar" class="btn btn-danger" ><span class="glyphicon glyphicon-trash"></span> Excluir</button>
        <a href="<?=$this->url('productbacklog',array('cod_projeto'=>$this->cod_projeto))?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>
    bloquerCampos();
    function excluir() {
        var formulario = document.getElementById('form_productbacklog');
        formulario.submit();

        return true;
    }

    function bloquerCampos() {
        var nomeProductBacklog = document.getElementById('nome_product_backlog');
        var descricaoProductBacklog = document.getElementById('descricao_product_backlog');
        var prioridadeProductBacklog = document.getElementById('prioridade_product_backlog');
        var codStatus = document.getElementById('cod_status');

        nomeProductBacklog.setAttribute('disabled', 'disabled');
        descricaoProductBacklog.setAttribute('disabled', 'disabled');
        prioridadeProductBacklog.setAttribute('disabled', 'disabled');
        codStatus.setAttribute('disabled', 'disabled');

    }

</script>