<div class="box-header with-border">
    <ol class="breadcrumb">
       <li class="breadcrumb-item"><a href="<?=$this->url('inicio')?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto')?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?=$this->url('projeto-gerenciar',array('cod_projeto'=>$this->cod_projeto))?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item active">Product Backlog</li>
    </ol>
</div>

<hr />
<a href="<?php echo $this->url('productbacklog-cadastrar', array('action' => 'cadastrar', 'cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-success" <?php if ($this->cod_tipo_participante != 1) { ?> disabled="disabled" <?php } ?>><span class="glyphicon glyphicon-file"></span> Novo Item Product Backlog</a>
<p></p>
<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome do Item</th>
            <th>Descrição do Item</th>
            <th>Prioridade</th>
            <th>Status</th>
            <th>Editar | Excluir</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($this->cod_tipo_participante == 1) {
            echo $this->partialLoop('partial_loop_listar.phtml', $this->partial_loop_listar);
        }
        if ($this->cod_tipo_participante == 2) {
            echo $this->partialLoop('partial_loop_listar_sm.phtml', $this->partial_loop_listar);
        }
        ?>   
    </tbody>
</table>