<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/inicio">Inicio</a></li>
        <li class="breadcrumb-item"><a href="/projeto">Projetos</a></li>
        <li class="breadcrumb-item active">Product Backlog</li>
    </ol>
</div>
<hr />
<a href="<?php echo $this->url('productbacklog-cadastrar', array('action' => 'cadastrar', 'cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-success">Novo Item Product Backlog</a>

<p></p>
<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Prioridade</th>
            <th>Status</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('partial_loop_listar.phtml', $this->partial_loop_listar) ?>  
    </tbody>
</table>