<tr>
    <td><?=$this->escapeHtml($this->codProductBacklog)?></td>
    <td><?=$this->escapeHtml($this->nomeProductBacklog)?></td>
    <td><?=$this->descricaoProductBacklog?></td>
    <td><?=$this->prioridadeProductBacklog?></td>
    <td><?=$this->codStatus?></td>
    <td>
        <a href="<?=$this->url('productbacklog-editar',array('cod_projeto'=>$this->codProjeto,'action'=>'editar','cod_productbacklog'=>$this->codProductBacklog)) ?>" class="btn btn-primary" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="<?=$this->url('productbacklog-excluir',array('cod_projeto'=>$this->codProjeto,'action'=>'excluir','cod_productbacklog'=>$this->codProductBacklog)) ?>" class="btn btn-danger" title="Excluir"><span class="glyphicon glyphicon-trash"></span></a>
    </td>    
</tr>
