<tr>
    <td><?=$this->escapeHtml($this->codProductBacklog)?></td>
    <td><?=$this->escapeHtml($this->nomeProductBacklog)?></td>
    <td><?=$this->descricaoProductBacklog?></td>
    <td><?=$this->prioridadeProductBacklog?></td>
    <td><?=$this->codStatus?></td>
    <td>
        <a href="<?php echo $this->url('participante-editar',array('action' => 'editar', 'cod_participante' => $this->codParticipante))?>" class="btn btn-info" >Editar</a>
        <a href="<?php echo $this->url('participante-excluir',array('action' => 'excluir', 'cod_participante' => $this->codParticipante))?>" class="btn btn-danger">Excluir</a>
    </td>    
</tr>
