<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item active">Product Backlog por Sprint</li>
    </ol>
</div>

<hr />
<div class="content">

    <div class="form-group">
        <label>Sprint:</label>
        <select name="cod_sprint" id="cod_sprint" class="form-control" onchange="location = this.value;">
            <option>Selecione...</option>
            <?= $this->partialLoop('partial_loop_sprint.phtml', $this->partial_loop_sprint) ?>  
        </select>
    </div> 
    <div class="form-group">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" disabled ><span class="glyphicon glyphicon-floppy-save"</span> Salvar</button>
        <a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
</div>