<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>">Gerenciar projeto</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('productbacklog-por-sprint', array('cod_projeto' => $this->cod_projeto)) ?>">Escolher Sprint</a></li>
        <li class="breadcrumb-item active">Product Backlog por Sprint</li>
    </ol>
</div>
<?php if (isset($_POST['botao_salvar'])) { ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <spant> Product Backlog por Sprint atualizado com sucesso!</spant>
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('productbacklog-por-sprint-listar', array('cod_projeto' => $this->cod_projeto, 'cod_sprint' => $this->cod_sprint)) ?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="alert alert-success">
    <p><b>Projeto:</b> <?= $this->projeto->nomeProjeto; ?></p>
    <p><b>Sprint:</b> <?= $this->sprint->nomeSprint; ?> &nbsp; <b>Descrição Sprint:</b> <?= $this->sprint->descricaoSprint; ?></p>
</div>
<div class="content">

    <!--    <div class="form-group">
            <label>Sprint:</label>
            <select name="cod_sprint" id="cod_sprint" class="form-control" onchange="location = this.value;">
                <option>Selecione...</option>
                <? $this->partialLoop('partial_loop_sprint.phtml', $this->partial_loop_sprint) ?>  
            </select>
        </div>-->
    <div class="form-group">

        
        <form name="product_backlog_por_sprint_form" method="post">
            <table class="table">
                <tr>
                    <td><label>Product Backlog:</label></td>
                    <td><label>Descrição Product Backlog</label></td>
                    <td><label>Product Backlog está ligado a sprint</label></td>
                </tr>
                <?php
                //echo $this->partialLoop('partial_loop_listar.phtml',$this->partial_loop_listar);
                foreach ($this->product_backlog as $lista) {
                    ?>
                    <tr>
                        <td>
                            <input type="checkbox" name="cod_product_backlog[]" id="cod_product_backlog" value="<?= $lista->codProductBacklogPb ?>" 
                            <?php if ($lista->codProductBacklog != null) { ?> 
                                       checked="checked" 
                                       <?php
                                   }
                                   if (isset($lista->codSprint) && $lista->codSprint != $this->cod_sprint) {
                                       ?>
                                       disabled="disabled"
                                       <?php
                                   }
                                   ?> > &nbsp;

                            <?php echo $lista->nomeProductBacklog; ?>
                        </td>
                        <td>
                            <?php echo $lista->descricaoProductBacklog; ?>
                        </td>
                        <td>
                            <?php if ($lista->codProductBacklog != null) { ?>  <a href="<?= $this->url('productbacklog-por-sprint-listar', array('cod_projeto' => $lista->codProjeto, 'cod_sprint' => $lista->codSprint)) ?>"> <?php
                                    echo $lista->nomeSprint." - " . $lista->descricaoSprint;
                                }
                                ?> </a>
                        </td>
                    </tr>


                <?php } ?>  
            </table>
    </div>

    <div class="form-group">
        <input type="hidden" name="cod_sprint" id="cod_sprint" value="<?= $this->cod_sprint ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
</form>
</div>



