<tr>
    <td>
        <input type="checkbox" name="cod_product_backlog[]" id="cod_product_backlog" value="<?= $this->codProductBacklogPb ?>" 
               <?php if ($this->codProductBacklog != null) { ?> 
               checked="checked" readonly="readonly"
                   <?php } ?> > &nbsp;
        <?= $this->nomeProductBacklog ?>&nbsp; 
    </td>
    <td>
        <?php if ($this->codProductBacklog != null){  ?> Este Product Backlog está ligado a sprint <a href="<?=$this->url('productbacklog-por-sprint-listar',array('cod_projeto'=>$this->codProjeto,'cod_sprint'=>$this->codSprint)) ?>"> <?php echo $this->nomeSprint; } ?> </a>
    </td>
</tr>
