<div class="box-header with-border">
    <h3 class="box-title">Cadastrar projeto</h3>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Dados salvos com sucesso!</b><br /><br />
                    Você deseja fazer alguma alteração?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Sim</button>
                    <a href="<?= $this->url('projeto-editar', array('action' => 'editar', 'cod_projeto' => $this->ultimoParticipante)) ?>" class="btn btn-default">Sim</a>
                    <a href="/projeto" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formProjeto = $this->form_projeto;
    //$formProjeto->setAttribute('action', $this->url('projeto-cadastrar'));
    $formProjeto->prepare();
    echo $this->form()->openTag($formProjeto);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('nome_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('descricao_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_inicio_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_fim_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('botao_salvar')); ?>
        <a href="<?= $this->url('projeto') ?>" class="btn btn-danger" >Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>
    $(function() {
        $( "#data_inicio_projeto" ).datepicker({
            showAnim: "fadeIn"
        });
    });
    $(function() {
        $( "#data_fim_projeto" ).datepicker({
            showAnim: "fadeIn"
        });
    });

//        $('#form_projeto').validate({
//            // Define as regras
//            rules: {
//                nome_projeto: {
//                    required: true,
//                },
//                
//                
//            },
//            // Define as mensagens de erro para cada regra
//            messages: {
//                nome_projeto: {
//                    required: "Campo Nome não pode ser vazio!",
//                },
//                
//            }
//        });
//    });
</script>