<div class="box-header with-border">
    <h3 class="box-title">Cadastrar projeto</h3>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Projeto cadastrado com sucesso!</b><br /><br />
                    Você deseja fazer alguma alteração?
                </div>
                <div class="modal-footer">
                    <a href="<?= $this->url('projeto-editar', array('action' => 'editar', 'cod_projeto' => $this->ultimoProjeto)) ?>" class="btn btn-default">Sim</a>
                    <a href="/projeto" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    
    $formProjeto = $this->form_projeto;
    //$formProjeto->setAttribute('action', $this->url('projeto-cadastrar'));
    $formProjeto->prepare();
    echo $this->form()->openTag($formProjeto);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('nome_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('descricao_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_inicio_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_fim_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('botao_salvar')); ?>
        <a href="<?= $this->url('projeto') ?>" class="btn btn-danger" >Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>
<input type="button" value="Calcular" onclick="calcularDiasProjeto()">
<script>
    
    $(function() {
        $( "#data_inicio_projeto" ).datepicker({
            showAnim: "fadeIn"
        });
    });
    $(function() {
        $( "#data_fim_projeto" ).datepicker({
            showAnim: "fadeIn"
        });
    });
    
//    function calcularDiasProjeto(){
        //var dataInicio =  document.getElementById('data_inicio_projeto').value;
        //var dataFim = document.getElementById('data_fim_projeto').value;
        
//       var dataInicioBR =  document.getElementById('data_inicio_projeto').value.split('/');
//       var dataInicioUSA = new Date(dataInicioBR[2],dataInicioBR[1] -1,dataInicioBR[0]);
//       
//       var dataFimBR = document.getElementById('data_fim_projeto').value.split('/');
//       var dataFimUSA = new Date(dataFimBR[2], dataFimBR[1] -1, dataFimBR[0]);
//        
//       var tempo = Math.abs(dataFimUSA.getTime() - dataInicioUSA.getTime());
//       var dias = Math.ceil(tempo / (1000 * 60 * 60 * 24)); 
//       
//       if(dias <= 15){
//           alert('O projeto não pode ter menos de 15 dias');
//           return false;
//       }
//   
//    }

//        $('#form_projeto').validate({
//            // Define as regras
//            rules: {
//                nome_projeto: {
//                    required: true,
//                },
//                
//                
//            },
//            // Define as mensagens de erro para cada regra
//            messages: {
//                nome_projeto: {
//                    required: "Campo Nome não pode ser vazio!",
//                },
//                
//            }
//        });
//    });
</script>