<div class="box-header with-border">    
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item active">Editar projeto</li>
    </ol>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == 1)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" ><!-- data-dismiss="modal" -->
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <spant> Projeto alterado com sucesso!</spant>
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('projeto')?>" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>

<hr />
<p>&nbsp;</p>
<div class="content">
    <?php
    $formProjeto = $this->form_projeto;
    //$formProjeto->setAttribute('action', $this->url('projeto-cadastrar'));
    $formProjeto->prepare();
    echo $this->form()->openTag($formProjeto);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('nome_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('descricao_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_inicio_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_fim_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_status')); ?>
    </div>
    <div class="form-group">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('projeto') ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>     
</div>

<script>

    $(function () {
        $("#data_inicio_projeto").datepicker({
            showAnim: "fadeIn"
        });
    });
    $(function () {
        $("#data_fim_projeto").datepicker({
            showAnim: "fadeIn"
        });
    });

//    $(document).ready(function () {
//        $('#cpf_participante').mask('999.999.999-99');
//        $('#telefone_participante').mask('(99) 99999-9999');
//
//        $('#form_participante').validate({
//            // Define as regras
//            rules: {
//                nome_participante: {
//                    required: true,
//                },
//                cpf_participante: {
//                    required: true,
//                    minlength: 14,
//                },
//                email_participante: {
//                    required: true,
//                    email: true,
//                },
//                tipo_participante: {
//                    required: true,
//                },
//            },
//            // Define as mensagens de erro para cada regra
//            messages: {
//                nome_participante: {
//                    required: "Campo Nome não pode ser vazio!",
//                },
//                cpf_participante: {
//                    required: "Campo CPF não pode ser vazio!",
//                    minlength: "O Campo CPF deve ter 11 números!"
//
//                },
//                email_participante: {
//                    required: "Campo E-mail não pode ser vazio!",
//                    email: "Formato email dever ter (@ e .com)!",
//                },
//                tipo_participante: {
//                    required: "Campo Tipo de Participante não pode ser vazio!",
//                },
//            }
//        });
//    });
</script>