<div class="box-header with-border">
    <h3 class="box-title">Excluir projeto</h3>
</div>
<?php
if (!isset($_POST['cod_participante'])) {
    ?>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Você está prestes a excluir um participante!</b><br /><br />
                    Você tem certeza que deseja excluir?
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-primary">Ver</button>
                    <button type="button" name="excluir" id="excluir" class="btn btn-danger" onclick="excluir();">Sim</button>
                    <a href="/participante" class="btn btn-warning">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>

<?php
}

if (isset($_POST['cod_participante'])) {
    
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                   Participante excluido com sucesso!
                </div>
                <div class="modal-footer">
                    <a href="/participante" class="btn btn-warning">Voltar</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>

<hr />
<div class="content">
    
</div>

<script>
//    bloquerCampos();
//    function excluir(){
//        var formulario = document.getElementById('form_participante');
//        formulario.submit();
//        
//        return true;
//    }
//    
//    function bloquerCampos(){
//        var nome_participante = document.getElementById('nome_participante');
//        var cpf_participante = document.getElementById('cpf_participante');
//        var telefone_participante = document.getElementById('telefone_participante');
//        var email_participante = document.getElementById('email_participante');
//        var cod_tipo_participante = document.getElementById('cod_tipo_participante');
//        
//        nome_participante.setAttribute('disabled','disabled');
//        cpf_participante.setAttribute('disabled','disabled');
//        telefone_participante.setAttribute('disabled','disabled');
//        email_participante.setAttribute('disabled','disabled');
//        cod_tipo_participante.setAttribute('disabled','disabled');
//    }
    
</script>