<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Participantes</a></li>
        <li class="breadcrumb-item active">Excluir Projeto</li>
    </ol>
</div>
<?php
if (!isset($_POST['cod_projeto'])) {
    ?>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"  aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Você está prestes a excluir um projeto!</b><br /><br />
                    Você tem certeza que deseja excluir?
                </div>
                <div class="modal-footer">
                    <button type="button" name="excluir" id="excluir" class="btn btn-primary" onclick="excluir();">Sim</button>
                    <a href="<?= $this->url('projeto') ?>" class="btn btn-warning">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>

    <?php
}

if (isset($_POST['cod_projeto'])) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    Projeto excluido com sucesso!
                </div>
                <div class="modal-footer">
                    <a href="<?=$this->url('projeto')?>" class="btn btn-warning">Voltar</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>

<hr />
<div class="content">
    <?php
    $formProjeto = $this->form_projeto;
    //$formProjeto->setAttribute('action', $this->url('projeto-cadastrar'));
    $formProjeto->prepare();
    echo $this->form()->openTag($formProjeto);
    ?>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('nome_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('descricao_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_inicio_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('data_fim_projeto')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formProjeto->get('cod_status')); ?>
    </div>   
     <div class="form-group">
        <a href="<?= $this->url('projeto-excluir', array('action' => 'excluir', 'cod_projeto' => $this->cod_participante)) ?>" class="btn btn-danger" ><span class="glyphicon glyphicon-trash"></span> Excluir</a>
        <a href="<?= $this->url('projeto') ?>" class="btn btn-warning" > <span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>      
</div>

<script>
    bloquerCampos();
    function excluir() {
        var formulario = document.getElementById('form_projeto');
        formulario.submit();

        return true;
    }

    function bloquerCampos() {
        var nomeProjeto = document.getElementById('nome_projeto');
        var descricaoProjeto = document.getElementById('descricao_projeto');
        var dataInicioProjeto = document.getElementById('data_inicio_projeto');
        var dataFimProjeto = document.getElementById('data_fim_projeto');
        var codParticipante = document.getElementById('cod_participante');
        var codStatus = document.getElementById('cod_status');

        nomeProjeto.setAttribute('disabled', 'disabled');
        descricaoProjeto.setAttribute('disabled', 'disabled');
        dataInicioProjeto.setAttribute('disabled', 'disabled');
        dataFimProjeto.setAttribute('disabled', 'disabled');
        codParticipante.setAttribute('disabled', 'disabled');
        codStatus.setAttribute('disabled', 'disabled');
    }

</script>