<style type="text/css">
    #tituloTabela{
        text-align: center;
        font-weight: 900;
        color: #003300;
    }
</style>
<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('projeto') ?>">Projetos</a></li>
        <li class="breadcrumb-item active">Gerenciar projeto</li>
    </ol>
</div>
<hr />
<div class="content">
    <div class="form-group">
        <a href="<?= $this->url('sprint', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary" >Sprint</a>
        <a href="<?= $this->url('productbacklog', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary" >Product Backlog</a>
        <a href="<?= $this->url('productbacklog-por-sprint', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary" >Product Backlog Por Sprint</a>
        <!--<a href="<? $this->url('participante-por-projeto', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary" >Participante por Projeto</a>-->
        <a href="<?= $this->url('projeto-relatorio', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-primary" >Gerar Relatório do Projeto</a>
    </div>
</div>

<table class="table table-bordered-green alert-success">
    <thead>
        <tr>
            <td colspan="3" id="tituloTabela"><h4>Dados do Projeto</h4> </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="2"><strong>Nome do projeto: </strong><?= $this->projetos['nome_projeto']; ?></td>
            <td><strong>Dono do projeto: </strong><?= $this->projetos['nome_participante']; ?></td>
        </tr>
        <tr>
            <td colspan="5"><strong>Descrição do Projeto:</strong> <?= $this->projetos['descricao_projeto']; ?></td>
        </tr>
        <tr>
            <td><strong>Data incio: </strong><?= $this->projetos['data_inicio_projeto']; ?></td>
            <td><strong>Data fim (prevista): </strong><?= $this->projetos['data_fim_projeto']; ?></td>
            <td><strong>Status: </strong><?= $this->projetos['descricao_status']; ?></td>
        </tr>
    </tbody>
</table>

<table class="table table-bordered-green alert-success">
    <thead>
        <tr>
            <td colspan="5" id="tituloTabela"><h4>Sprint</h4></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_sprint->sprintEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_sprint->sprintEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_sprint->sprintParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_sprint->sprintFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_sprint->totalSprint ?></td>
        </tr>
<!--        <tr>
            <td colspan="5"><strong>Observações:</strong></td>
        </tr>
        <tr>
            <td colspan="5">
                - Atenção 1 sprint está atrasada 2 dias.<br /> 
                - 1 Sprint pra ser finalizada 25/03/2017.<br />
            </td>
        </tr>-->
    </tbody>
</table>

<table class="table table-bordered-green alert-success">
    <thead>
        <tr>
            <td colspan="5" id="tituloTabela"><h4>Product Backlog</h4></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_product_backlog->productBacklogEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_product_backlog->productBacklogEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_product_backlog->productBacklogParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_product_backlog->productBacklogFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_product_backlog->totalProductBacklog ?></td>
        </tr>
        <tr>
            <td><strong>Prioridades</strong></td>
            <td><strong>Alta: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeAlta ?></td>
            <td><strong>Média: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeMedia ?></td>
            <td colspan="2"><strong>Baixa: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeBaixa ?></td>

            <!--        </tr>
                    <tr>
                        <td colspan="5"><strong>Observações:</strong></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            - Antenção! Você tem muitos itens com prioridade alta.<br /> 
                            - Antenção! Você tem muitos itens parados.<br /> 
                        </td>
                    </tr>-->
    </tbody>
</table>

<table class="table table-bordered-green alert-success">
    <thead>
        <tr>
            <td colspan="5" id="tituloTabela"><h4>Sprint Backlog</h4></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_sprint_backlog->sprintBacklogParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_sprint_backlog->sprintBacklogFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_sprint_backlog->totalSprintBacklog ?></td>
        </tr>
<!--        <tr>
            <td colspan="5"><strong>Observações:</strong></td>
        </tr>
        <tr>
            <td colspan="5">
                - Atenção! 2 sprint backlogs estão atrasada 1 dias.<br /> 
                - Atenção! 1 sprint backlog está atrasada 1 dias.<br /> 
                - Atenção! 3 sprint backlog pra serem finalizadas 26/03/2017.<br />
                - Atenção! 1 sprint backlog pra ser finalizada 25/03/2017.<br />
            </td>
        </tr>-->
    </tbody>
</table>



