<div class="box-header with-border">
     <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/inicio">Inicio</a></li>
        <li class="breadcrumb-item active">Projetos</li>
    </ol>
</div>

<hr />
<a href="<?php echo $this->url('projeto-cadastrar', array('action' => 'cadastrar')) ?>" class="btn btn-success"><span class="glyphicon glyphicon-file"></span> Novo Projeto</a>
<p></p>
<table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Data Inicio</th>
            <th>Data Fim</th>
            <th>Dono do projeto</th>
            <th>Status</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('partial_loop_listar.phtml', $this->partial_loop_listar) ?>  
    </tbody>
</table>
