<?php
$dataInicioProjeto = date_create($this->dataInicioProjeto);
$dataFimProjeto = date_create($this->dataFimProjeto);
?>
<tr>
    <td><?= $this->codProjeto ?></td>
    <td><?= $this->escapeHtml($this->nomeProjeto) ?></td>
    <td><?= $this->descricaoProjeto ?></td>
    <td><?= date_format($dataInicioProjeto, 'd/m/Y') ?></td>
    <td><?= date_format($dataFimProjeto, 'd/m/Y') ?></td>
    <td><?= $this->nomeParticipante ?></td>    
    <td><?= $this->descricaoStatus ?></td>    
    <!-- para botões na mesma linha -->
    <td>
        <a href="<?=$this->url('projeto-gerenciar',array('action' => 'gerenciar', 'cod_projeto' => $this->codProjeto))?>" class="btn btn-warning" id="<?=$this->codProjeto?>" title="Gerenciar Projeto"><span class="glyphicon glyphicon-cog"></span></a><!-- Gerenciar -->
        <a href="<?=$this->url('projeto-editar',array('action' => 'editar', 'cod_projeto' => $this->codProjeto))?>" class="btn btn-primary" id="<?=$this->codProjeto?>" title="Editar"><span class="glyphicon glyphicon-edit"></span></a><!-- Editar -->
        <a href="<?=$this->url('projeto-excluir',array('action' => 'excluir', 'cod_projeto' => $this->codProjeto))?>" class="btn btn-danger" id="<?=$this->codProjeto?>" title="Excluir"><span class="glyphicon glyphicon-trash"></span></a><!--Excluir -->
    </td>
</tr>

<script>

    function marcarProjeto(cod_projeto) {
        var codProjeto = cod_projeto.value;

        var editar = document.getElementById('editar-btn');
        var excluir = document.getElementById('excluir-btn');
        var sprint = document.getElementById('sprint-btn');
        var productbacklog = document.getElementById('productbacklog-btn');
        var relatorio = document.getElementById('relatorio-btn');

        editar.removeAttribute('disabled');
        excluir.removeAttribute('disabled');
        sprint.removeAttribute('disabled');
        productbacklog.removeAttribute('disabled');
        relatorio.removeAttribute('disabled');

        editar.setAttribute('href', 'projeto-editar/' + codProjeto);
        excluir.setAttribute('href', 'projeto-excluir/' + codProjeto);
        sprint.setAttribute('href', 'projeto/' + codProjeto + '/sprint');
        productbacklog.setAttribute('href', 'projeto/' + codProjeto + '/productbacklog');
        relatorio.setAttribute('href', 'projeto/' + codProjeto + '/sprint');
        
        

    }

</script>

