
<style>
    body {
        font-family: Arial, sans-serif;
    }
    .container {
        width:573px;
        margin: auto;
        padding: 10px;
        border:1px solid #000;
    }
    h1{text-align: center;}
    h2{text-align: center;}

    .dataDeGeracao{font-size: 12px; text-align: right;}
</style>
<!--<div class="container">-->

<h1>My Easy Scrum</h1>
<h2>Relatório do Projeto: <?= $this->dados_projeto['nome_projeto'] ?></h2>
<hr />
<h3>Dados do Projeto</h3>
<strong>Nome do projeto: </strong><?= $this->dados_projeto['nome_projeto']; ?><br/>
<strong>Dono do projeto: </strong><?= $this->dados_projeto['nome_participante']; ?><br/>
<strong>Descrição do Projeto:</strong> <?= $this->dados_projeto['descricao_projeto']; ?><br/>
<strong>Data incio: </strong><?= $this->dados_projeto['data_inicio_projeto']; ?><br/>
<strong>Data fim (prevista): </strong><?= $this->dados_projeto['data_fim_projeto']; ?><br/>
<strong>Status: </strong><?= $this->dados_projeto['descricao_status']; ?><br/>
<hr />
<h3>Sprint</h3>
<strong>Em Aberto: </strong><?= $this->dados_sprint->sprintEmAberto ?><br/>
<strong>Em Andamento: </strong><?= $this->dados_sprint->sprintEmAndamento ?><br/>
<strong>Finalizado: </strong><?= $this->dados_sprint->sprintParado ?><br/>
<strong>Parado: </strong><?= $this->dados_sprint->sprintFinalizado ?><br/>
<br />
<strong>Total: </strong><?= $this->dados_sprint->totalSprint ?><br/>
<hr />
<h3>Product Backlog</h3>
<strong>Em Aberto: </strong><?= $this->dados_product_backlog->productBacklogEmAberto ?><br/>
<strong>Em Andamento: </strong><?= $this->dados_product_backlog->productBacklogEmAndamento ?><br/>
<strong>Finalizado: </strong><?= $this->dados_product_backlog->productBacklogParado ?><br/>
<strong>Parado: </strong><?= $this->dados_product_backlog->productBacklogFinalizado ?><br/>
<h4>Prioridades</strong></h4>
<strong>Alta: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeAlta ?><br/>
<strong>Média: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeMedia ?><br/>
<strong>Baixa: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeBaixa ?><br/>
<br />
<strong>Total: </strong><?= $this->dados_product_backlog->totalProductBacklog ?><br/>
<hr />
<h3>Sprint Backlog</h3>
<strong>Em Aberto: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAberto ?><br/>
<strong>Em Andamento: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAndamento ?><br/>
<strong>Finalizado: </strong><?= $this->dados_sprint_backlog->sprintBacklogParado ?><br/>
<strong>Parado: </strong><?= $this->dados_sprint_backlog->sprintBacklogFinalizado ?><br/>
<br/>
<strong>Total: </strong><?= $this->dados_sprint_backlog->totalSprintBacklog ?><br/>
<hr />
<!--</div>-->


<div class="dataDeGeracao">
    Gerado em: 
    <?php
    date_default_timezone_set('America/Sao_Paulo');
    $date = date('d/m/Y H:i');
    echo $date;
    ?>
</div>