


<style>
    body {
        font-family: Arial, sans-serif;
    }
    .container {
        width:573px;
        margin: auto;
        padding: 10px;
        border:1px solid #000;
    }
    h1{text-align: center;}
    h2{text-align: center;}
</style>
<!--<div class="container">-->

<h1>My Easy Scrum</h1>
<br />
<h2>Relatório do Projeto x</h2>
<h3>Informações do Projeto</h3>
<hr />
<strong>Em Aberto: </strong><?= $this->dados_product_backlog->productBacklogEmAberto ?>
<strong>Em Andamento: </strong><?= $this->dados_product_backlog->productBacklogEmAndamento ?>
<strong>Finalizado: </strong><?= $this->dados_product_backlog->productBacklogParado ?>
<strong>Parado: </strong><?= $this->dados_product_backlog->productBacklogFinalizado ?>
<strong>Total: </strong><?= $this->dados_product_backlog->totalProductBacklog ?>
<!--</div>-->



<?php
date_default_timezone_set('America/Sao_Paulo');
$date = date('d/m/Y H:i');
echo $date;
?>