<html>
<style>
    body {
        font-family: Arial, sans-serif;
    }
    .container {
        width:573px;
        margin: auto;
        padding: 10px;
        border:1px solid #000;
    }

    h1{text-align: center;}
    h2{text-align: center;}
    hr{
        border-top: 0px solid #fff;
      border-bottom: 1px solid #000;
      color: #fff;
      background-color: #fff;
     }

    table {border-collapse: collapse;width: 100%;}
    thead,th{text-align: left; background-color: #aaa;}
    table, tr, td{border-bottom:1px solid #000; }
    table, thead{border-bottom:1px solid #000; }
    .dataDeGeracao{font-size: 12px; text-align: right;}
</style>
<!--<div class="container">-->
<head>
    <title>Relatório do projeto</title>
</head>
<body>
<h1>My Easy Scrum</h1>
<h2>Relatório do Projeto: <?= $this->dados_projeto['nome_projeto'] ?></h2>
<hr />
<h3>Dados do Projeto</h3>
<strong>Nome do projeto: </strong><?= $this->dados_projeto['nome_projeto']; ?><br/>
<strong>Dono do projeto: </strong><?= $this->dados_projeto['nome_participante']; ?><br/>
<strong>Descrição do Projeto:</strong> <?= $this->dados_projeto['descricao_projeto']; ?><br/>
<strong>Data incio: </strong><?= $this->dados_projeto['data_inicio_projeto']; ?><br/>
<strong>Data fim (prevista): </strong><?= $this->dados_projeto['data_fim_projeto']; ?><br/>
<strong>Status: </strong><?= $this->dados_projeto['descricao_status']; ?><br/>
<hr />
<h3>Sprint</h3>

<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Duração</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->sprints as $sprints) { ?>
            <tr>
                <td><?= $sprints->nomeSprint ?></td>
                <td><?= $sprints->descricaoSprint ?></td>
                <td><?= $sprints->tempoSprint ?>&nbsp;Dias</td>
                <td><?= $sprints->descricaoStatus ?></td>
            </tr>
        <?php } ?>  
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_sprint->sprintEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_sprint->sprintEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_sprint->sprintParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_sprint->sprintFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_sprint->totalSprint ?></td>
        </tr>
    </thead>
</table>
<br />
<hr />
<h3>Product Backlog</h3>
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Prioridade</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->productBacklogs as $productBacklogs) { ?>
            <tr>
                <td><?= $productBacklogs->nomeProductBacklog ?></td>
                <td><?= $productBacklogs->descricaoProductBacklog ?></td>
                <td><?php
                    switch ($productBacklogs->prioridadeProductBacklog) {
                        case 1;
                            echo 'Alta';
                            break;
                        case 2;
                            echo 'Média';
                            break;
                        case 3;
                            echo 'Baixa';
                            break;
                    }
                    ?></td>
                <td><?= $productBacklogs->descricaoStatus ?></td>
            </tr>
        <?php } ?>  
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_product_backlog->productBacklogEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_product_backlog->productBacklogEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_product_backlog->productBacklogParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_product_backlog->productBacklogFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_product_backlog->totalProductBacklog ?></td>
        </tr>
    </thead>
</table>
<br>
<table>
    <thead>
        <tr>
            <td><strong>Priorides </strong></td>
            <td><strong>Alta: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeAlta ?></td>
            <td><strong>Média: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeMedia ?></td>
            <td><strong>Baixa: </strong><?= $this->dados_product_backlog->productBacklogPrioridadeBaixa ?></td>
        </tr>
    </thead>
</table>
<br />
<hr />
<h3>Sprint Backlog</h3>
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Tempo</th>
            <th>Status</th>
            <th>Atribuido</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->sprintBacklogs as $sprintBacklogs) { ?>
            <tr>
                <td><?= $sprintBacklogs->nomeSprintBacklog ?></td>
                <td><?= $sprintBacklogs->descricaoSprintBacklog ?></td>
                <td><?= $sprintBacklogs->tempoSprintBacklog ?>&nbsp;Horas</td>
                <td><?= $sprintBacklogs->descricaoStatus ?></td>
                <td><?= $sprintBacklogs->nomeParticipante ?></td>
            </tr>
        <?php } ?>  
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <td><strong>Em Aberto: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAberto ?></td>
            <td><strong>Em Andamento: </strong><?= $this->dados_sprint_backlog->sprintBacklogEmAndamento ?></td>
            <td><strong>Finalizado: </strong><?= $this->dados_sprint_backlog->sprintBacklogParado ?></td>
            <td><strong>Parado: </strong><?= $this->dados_sprint_backlog->sprintBacklogFinalizado ?></td>
            <td><strong>Total: </strong><?= $this->dados_sprint_backlog->totalSprintBacklog ?></td>
        </tr>
    </thead>
</table>
<br>

<div class="dataDeGeracao">
    Relatório gerado em 
    <?php
    date_default_timezone_set('America/Sao_Paulo');
    $data = date('d/m/Y');
    $hora = date('H:i');
    echo "$data às $hora";
    ?>
</div>
</body>
</html>