<div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
<!--                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>-->
                    <h4 class="modal-title" id="myModalLabel"><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">

                    <!--<b>Projeto cadastrado com sucesso!</b><br /><br />-->
                    Usuário e/ou senha inválidos.
                </div>
                <div class="modal-footer">
                    <a href="/login" class="btn btn-primary">Voltar</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
