<div class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="text-center">My Easy Scrum - MES</h2>
                <h4 class="text-center">Autenticação do usuário</h4>
            </div>
            <div class="modal-body">
                <?php $this->Notificacoes(); ?>
                <?php
                $formLogin = $this->form_login;
                $formLogin->prepare();
                echo $this->form()->openTag($formLogin);
                ?>

                <div class="form-group">
                    <?= $this->formRow($formLogin->get('email_participante')); ?> 
                </div>
                <div class="form-group">
                    <?= $this->formRow($formLogin->get('senha_participante')); ?>
                </div>

                <div class="form-group">
                    <div>
                        <button type="submit" name="botao_entrar" id="botao_entrar" class="btn btn-primary btn-lg btn-block" >Entrar <span class="glyphicon glyphicon-arrow-right"></span></button>
                    </div>
                </div>
                <div style="display: inline">
                    <a href="<?php echo $this->url('criarcontaproductowner') ?>" >
                        Criar conta
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url('recuperasenha') ?>">
                        Esqueci a senha
                    </a></div>

            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>     
    </div>
</div>

<script>

    $(document).ready(function () {

        $('#form_login').validate({
            // Define as regras
            rules: {
                email_participante: {
                    required: true,
                    email: true,
                },
                senha_participante: {
                    required: true,
                    minlength: 6,
                    maxlength: 12,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                email_participante: {
                    required: "Campo E-mail não pode ser vazio",
                    email: "Formato email dever ter (@ e .com)",
                },
                senha_participante: {
                    required: "Campo Senha não pode ser vazio!",
                    minlength: "A senha dever ter no mínimo 6 caracteres",
                    maxlength: "A senha dever ter no máximo 12 caracteres",
                }
            }
        });
    });
</script>