<div class="container-fluid">    
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">My Easy Scrum | Login</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Esqueceu a senha?</a></div>
            </div>     

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <?php
                $formLogin = $this->form_login;
                $formLogin->setAttribute('action', $this->url('autenticacao', array('action' => 'autenticacao')));
                $formLogin->prepare();
                echo $this->form()->openTag($formLogin);
                ?>

                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <?= $this->formRow($formLogin->get('email_participante')); ?>                                       
                </div>

                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <?= $this->formRow($formLogin->get('senha_participante')); ?>
                </div>



<!--                <div class="input-group">
                    <div class="checkbox">
                        <label>
                            <input id="login-remember" type="checkbox" name="remember" value="1"> Lembrar
                        </label>
                    </div>
                </div>-->


                <div style="margin-top:10px" class="form-group">
                    <!-- Button -->

<!--                    <div class="btn btn-danger">-->
                        <?= $this->formRow($formLogin->get('botao_entrar')); ?>
                        <!--<a id="btn-fblogin" href="#" class="btn btn-primary">Login com Facebook</a>-->
                        
                    <!--</div>-->
                </div>


                <div class="form-group">
                    <div class="col-md-12 control">
                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                            
                            <a href="<?php echo $this->url('criarcontaproductowner') ?>" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                Criar conta
                            </a>
                        </div>
                    </div>
                </div>    
                <?php echo $this->form()->closeTag(); ?>     



            </div>                     
        </div>  
 <script>
$(document).ready(function () {

        $('#form_login').validate({
            // Define as regras
            rules: {
                email_participante: {
                    required: true,
                    email: true,
                },
                senha_participante: {
                    required: true,
                    minlength: 6,
                    maxlength: 12,
                },
                
            },
            // Define as mensagens de erro para cada regra
            messages: {
               
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                senha_participante: {
                    required: "Campo Senha não pode ser vazio!",
                    minlength: "A senha dever ter no mínimo 6 caracteres",
                    maxlength: "A senha dever ter no máximo 12 caracteres",
                }
            }
        });
    });
</script>