<div class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="text-center">My Easy Scrum - MES</h2>
                <h4 class="text-center">Autenticação do usuário</h4>
            </div>
            <div class="modal-body">
               
                <?php
                $formLogin = $this->form_login;
                $formLogin->setAttribute('action', $this->url('autenticacao', array('action' => 'autenticacao')));
                $formLogin->prepare();
                echo $this->form()->openTag($formLogin);
                ?>

                <div class="form-group">
                    <?= $this->formRow($formLogin->get('email_participante')); ?> 
                </div>
                <div class="form-group">
                    <?= $this->formRow($formLogin->get('senha_participante')); ?>
                </div>

                <div class="form-group">
                    <div>
                        <?= $this->formRow($formLogin->get('botao_entrar')); ?>
                    </div>
                </div>
                <span>
                    <a href="<?php echo $this->url('criarcontaproductowner') ?>" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                        Criar conta
                    </a></p></span>

            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>     
    </div>
</div>

<script>

    $(document).ready(function () {

        $('#form_login').validate({
            // Define as regras
            rules: {
                email_participante: {
                    required: true,
                    email: true,
                },
                senha_participante: {
                    required: true,

                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                email_participante: {
                    required: "Campo E-mail não pode ser vazio",
                    email: "Formato email dever ter (@ e .com)",
                },
                senha_participante: {
                    required: "Campo Senha não pode ser vazio!",

                }
            }
        });
    });
</script>