<div class="box-header with-border">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('inicio') ?>">Inicio</a></li>
        <li class="breadcrumb-item"><a href="<?= $this->url('participante') ?>">Participante</a></li>
        <li class="breadcrumb-item active">Projeto por Participante</li>
    </ol>
</div>

<hr />
<?php // var_dump($this->participante_por_projeto);?>
<?php echo $this->codParticipante ?>
<form method="post">
    <table id="data_table" class="table data_tables table-striped table-hover table-bordered dataTable no-footer" role="grid" aria-describedby="data_table_info" style="width: 100%;" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th><input type="checkbox" name="todos" > &nbsp; Projeto</td>
                <td>Dono do Projeto</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->projeto_por_participante as $projeto) { ?>
                <tr>
                    <td><input type="checkbox" name="projeto[]" value="<?= $projeto->codProjeto ?>"
                               <?php if ($projeto->codProjeto != null) { ?> checked="checked" <?php } ?>> 
                    <?= $projeto->nomeProjeto ?></td>
                    <td><?= $projeto->nomeParticipante ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <div class="form-group">
        <input type="hidden" name="cod_sprint" id="cod_sprint" value="<?= $this->cod_sprint ?>">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('projeto-gerenciar', array('cod_projeto' => $this->cod_projeto)) ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
</form>




