<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('My Easy Scrum - MES') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                //CSS DataTables
                ->prependStylesheet($this->basePath('plugin/datatables/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('plugin/datatables/css/dataTables.bootstrap.min.css'))
                //CSS Datepicker
                ->prependStylesheet($this->basePath('plugin/datepicker/datepicker.css'))
                //CSS Bootstrap
                ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                //JQuery Validade JS
                ->prependFile($this->basePath('plugin/jquery-validation-1.15.0/additional/extension.js'))
                ->prependFile($this->basePath('plugin/jquery-validation-1.15.0/dist/additional-methods.js'))
                ->prependFile($this->basePath('plugin/jquery-validation-1.15.0/dist/jquery.validate.min.js'))
                ->prependFile($this->basePath('plugin/jquerymask/jquery.mask.js'))
                //Jquery datepiker
                ->prependFile($this->basePath('plugin/datepicker/bootstrap-datepicker.js'))

                //Datatables
                ->prependFile($this->basePath('plugin/datatables/js/dataTables.bootstrap.min.js'))
                ->prependFile($this->basePath('plugin/datatables/js/jquery.dataTables.min.js'))

                //Jquery 
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))

//                 ->prependFile('http://code.jquery.com/jquery-1.10.2.js')



        ;
        ?>

    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo 'My Easy Scrum - MES'; ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        <li><a href="<?php echo $this->url('projeto') ?>">Gerenciar projeto</a></li>
                        <li><a href="<?php echo $this->url('participante') ?>">Participante</a></li>
                        <li><a href="<?php echo $this->url('alterarsenha') ?>">Alterar senha</a></li>
                        <li><a href="<?php echo $this->url('sair') ?>">Sair</a></li>

                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('Todos os direitos reservados.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
            $(document).ready(function () {
                $('.data_tables').dataTable({
                    "order": [[1, "desc"]],
                    "oLanguage": {
                        "sProcessing": "Aguarde enquanto os dados são carregados ...",
                        "sLengthMenu": "Mostrar _MENU_ registros por página",
                        "sZeroRecords": "Nenhum registro correspondente ao criterio encontrado",
                        "sInfoEmtpy": "Exibindo 0 a 0 de 0 registros",
                        "sInfo": "Exibindo de _START_ a _END_ de _TOTAL_ registros",
                        "sInfoFiltered": "",
                        "sSearch": "Procurar",
                        "oPaginate": {
                            "sFirst": "<< Primeiro",
                            "sPrevious": "< Anterior",
                            "sNext": "Próximo >",
                            "sLast": "Último >>"
                        }
                    }
                });

            });
        </script>
    </body>
</html>
