<div class="box-header with-border">
    <h3 class="box-title">Alterar Senha</h3>
</div>
<hr />
<?php $this->Notificacoes(); ?>
<div class="content">
    <?php
    $formSenha = $this->form_senha;
    $formSenha->prepare();
    echo $this->form()->openTag($formSenha);
    ?>
    <div class="form-group">
        <?= $this->formRow($formSenha->get('senha_atual')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSenha->get('nova_senha')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSenha->get('confirma_senha')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formSenha->get('botao_salvar')); ?>
        <a href="<?= $this->url('inicio') ?>" class="btn btn-danger" >Cancelar</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>     
</div>

<script>

    $(document).ready(function () {

        $('#form_senha').validate({
            // Define as regras
            rules: {
                senha_atual: {
                    required: true,
                },
                nova_senha: {
                    required: true,
                    minlength: 6,
                    maxlength: 12,
                },
                confirma_senha: {
                    required: true,
                    equalTo: '#nova_senha'

                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                senha_atual: {
                    required: "A senha atual deve ser informada",
                },
                nova_senha: {
                    required: "Campo Senha não pode ser vazio!",
                    minlength: "A senha dever ter no mínimo 6 caracteres",
                    maxlength: "A senha dever ter no máximo 12 caracteres",
                },
                confirma_senha: {
                    required: "Campo Confirma Senha não pode ser vazio!",
                    equalTo: "Senhas não conferem!",
                },
            }
        });
    });
</script>