<div class="box-header with-border">
    <h3 class="box-title">Alterar Senha</h3>
</div>
<hr />
<?php
if (isset($_POST['botao_salvar'])) {
    if ($this->flashMessenger()->hasMessages()) {
        ?>
        <div class='modal fade' id='myModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
            <div class='modal-dialog' role='document'>
                <div class='modal-content'>
                    <div class='modal-header'>
                        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                            <span aria-hidden='true'>&times;</span>
                        </button>
                        <h4 class='modal-title' id='myModalLabel'><b>Atenção!</b></h4>
                    </div>
                    <div class='modal-body'>
                        <?php
                        $messages = $this->flashMessenger()->getMessages();
                        foreach ($messages as $message) {
                            echo $message;
                        }
                        ?>
                    </div>
                    <div class='modal-footer'>
                        <a href='/inicio' class='btn btn-default'>Ok</a>
                    </div>
                </div>
            </div>
        </div>
        <script>$('#myModal').modal();</script>
        <?php
    }
}
?>
<div class="content">
    <?php
    $formSenha = $this->form_senha;
    $formSenha->prepare();
    echo $this->form()->openTag($formSenha);
    ?>
    <div class="form-group">
<?= $this->formRow($formSenha->get('senha_atual')); ?>
    </div>
    <div class="form-group">
<?= $this->formRow($formSenha->get('nova_senha')); ?>
    </div>
    <div class="form-group">
<?= $this->formRow($formSenha->get('confirma_senha')); ?>
    </div>
    <div class="form-group">
    <?= $this->formRow($formSenha->get('botao_salvar')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>     
</div>

<script>

    $(document).ready(function () {

        $('#form_senha').validate({
            // Define as regras
            rules: {
                senha_atual: {
                    required: true,
                },
                nova_senha: {
                    required: true,
                    minlength: 6,
                    maxlength: 12,
                },
                confirma_senha: {
                    required: true,
                    equalTo: '#nova_senha'

                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                senha_atual: {
                    required: "A senha atual deve ser informada",
                },
                nova_senha: {
                    required: "Campo Senha não pode ser vazio!",
                    minlength: "A senha dever ter no mínimo 6 caracteres",
                    maxlength: "A senha dever ter no máximo 12 caracteres",
                },
                confirma_senha: {
                    required: "Campo Confirma Senha não pode ser vazio!",
                    equalTo: "Senhas não conferem!",
                },
            }
        });
    });
</script>