<div class="box-header with-border">    
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/inicio">Inicio</a></li>
        <li class="breadcrumb-item"><a href="/participante">Participantes</a></li>
        <li class="breadcrumb-item active">Cadastrar participante</li>
    </ol>
</div>
<?php if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="close" aria-label="Close" >
                        <!--<a href="/participante"> <span class="glyphicon glyphicon-remove "></span></a>-->
                    </div>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabéns!</b></h4>
                </div>
                <div class="modal-body">
                    <spant> Participante cadastrado com sucesso!</spant>
                </div>
                <div class="modal-footer">
                    <a href="/participante" class="btn btn-primary">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />
<div class="content">

    <?php
    $formParticipante = $this->form_participante;
    $formParticipante->prepare();
    echo $this->form()->openTag($formParticipante);
    ?>

    <div class="form-group">
        <?= $this->formRow($formParticipante->get('nome_participante')); ?>

    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('cpf_participante')); ?>
        <div id="cpf-error"><ul><li><?= $this->validadeCpf ?></li></ul></div>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('telefone_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('email_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('cod_tipo_participante')); ?>
    </div>
    <div class="form-group">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('participante') ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>     
</div>
<script>
    function cpf() {
        var msCpfInvalido = document.getElementById('cpf-error');
        msCpfInvalido.innerHTML = '';

    }

    $(document).ready(function () {
        $('#cpf_participante').mask('999.999.999-99');

        $('#telefone_participante').mask('(00) 0000-00009');
        $('#telefone_participante').blur(function (event) {
            if ($(this).val().length == 15) { // Celular com 9 dígitos + 2 dígitos DDD e 4 da máscara
                $('#telefone_participante').mask('(00) 00000-0009');
            } else {
                $('#telefone_participante').mask('(00) 0000-00009');
            }
        });
        $('#form_participante').validate({
            // Define as regras
            rules: {
                nome_participante: {
                    required: true,
                },
                cpf_participante: {
                    required: true,
                    minlength: 14,
                },
                telefone_participante: {
                    minlength: 14,
                },
                email_participante: {
                    required: true,
                    email: true,
                },
                cod_tipo_participante: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_participante: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_participante: {
                    required: "Campo CPF não pode ser vazio!",
                    minlength: "O Campo CPF deve ter 11 números!"

                },
                telefone_participante: {
                    minlength: "O Campo Telefone deve ter 10 ou 11 dígitos!"

                },
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                cod_tipo_participante: {
                    required: "Campo Tipo de Participante não pode ser vazio!",
                },
            }
        });
    });



</script>