<div class="box-header with-border">
	<h3 class="box-title">Criar Conta Product Owner</h3>
</div>
<?php

if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Usuário criado com sucesso!</b><br /><br />
                    Você deseja acessar o sistema?
                </div>
                <div class="modal-footer">
                    <a href="/inicio" class="btn btn-default">Sim</a>
                    <a href="/sair" class="btn btn-danger">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>
<hr />

<div class="tab-content">

                <?php
                //echo $this->retorno;
                $formParticipante = $this->form_participante;
                //$formParticipante->setAttribute('action', $this->url('criarcontaproductowner'));
                $formParticipante->prepare();
                echo $this->form()->openTag($formParticipante);
                ?>

        <div class="form-group">
            <?= $this->formRow($formParticipante->get('nome_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('cpf_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('telefone_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('email_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('senha_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('confirma_senha_participante')); ?>
        </div>
             <input type="hidden" name="cod_tipo_participante" id="cod_tipo_participante" value="1">
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('botao_salvar')); ?>
            <a href="<?=$this->url('login') ?>" class="btn btn-danger" >Cancelar</a>
        </div>
               
                <?php echo $this->form()->closeTag(); ?>     
</div>
<?php echo $this->message; ?>
    <script>
//    habilitarAba();
//    
//    function habilitarAba(){
//    var post = <?$this->retorno ?>;
//    var dadosPessoais = document.getElementById('dados_pessoais_link');
//    var dadosUsuario = document.getElementById('dados_usuario_link');
//    var divDadosPessoais =  document.getElementById('dados_pessoais');
//    var divDadosUsuario =  document.getElementById('dados_usuario');
//    
//        if(post == true){
//            dadosPessoais.className = 'nav-item';
//            dadosUsuario.className = 'nav-item active';
////            divDadosPessoais.className = 'tab-pane';
//            divDadosUsuario.className = 'tab-pane active';
//        }
//    }


   $(document).ready(function () {
        $('#cpf_participante').mask('999.999.999-99');
        $('#telefone_participante').mask('(99) 99999-9999');
        
        $('#form_participante').validate({
            // Define as regras
            rules: {
                nome_participante: {
                    required: true,
                },
                cpf_participante: {
                    required: true,
                    minlength: 14,
                },
                email_participante: {
                    required: true,
                    email: true,
                },
                senha_participante: {
                    required: true,
                    minlength: 6,
                    maxlength: 12,
                },
                confirma_senha_participante: {
                    required: true,
                    equalTo: '#senha_participante'
                    
                },

            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_participante: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_participante: {
                    required: "Campo CPF não pode ser vazio!",
                    minlength: "O Campo CPF deve ter 11 números!"
                    
                },
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                senha_participante: {
                    required: "Campo Senha não pode ser vazio!",
                    minlength: "A senha dever ter no mínimo 6 caracteres",
                    maxlength: "A senha dever ter no máximo 12 caracteres",
                },
                confirma_senha_participante: {
                    required: "Campo Confirma Senha não pode ser vazio!",
                    equalTo: "Senhas não conferem!",
                },
            }
        });
    });
</script>



    