<div class="box-header with-border">
	<h3 class="box-title">Criar Conta Product Owner</h3>
</div>
<hr />
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item active" id="dados_pessoais_link">
    <a class="nav-link " data-toggle="tab" href="#dados_pessoais" role="tab">Dados Pessoais</a>
  </li>
  <li class="nav-item" id="dados_usuario_link">
    <a class="nav-link " data-toggle="tab" href="#dados_usuario" role="tab">Dados do Usuário</a>
  </li>
</ul>
<br />


<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="dados_pessoais" role="tabpanel">
         

                <?php
                //echo $this->retorno;
                $formParticipante = $this->form_participante;
                //$formParticipante->setAttribute('action', $this->url('criarcontaproductowner'));
                $formParticipante->prepare();
                echo $this->form()->openTag($formParticipante);
                ?>

        <div class="form-group">
            <?= $this->formRow($formParticipante->get('nome_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('cpf_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('telefone_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('email_participante')); ?>
        </div>
             <input type="hidden" name="cod_tipo_participante" id="cod_tipo_participante" value="1">
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('botao_salvar')); ?>
            <a href="<?=$this->url('login') ?>" class="btn btn-danger" >Cancelar</a>
        </div>
               
                <?php echo $this->form()->closeTag(); ?>     
    </div>
    
  <div class="tab-pane" id="dados_usuario" role="tabpanel">
      quatro
  </div>
</div>

    <script>
//    habilitarAba();
//    
//    function habilitarAba(){
//    var post = <?$this->retorno ?>;
//    var dadosPessoais = document.getElementById('dados_pessoais_link');
//    var dadosUsuario = document.getElementById('dados_usuario_link');
//    var divDadosPessoais =  document.getElementById('dados_pessoais');
//    var divDadosUsuario =  document.getElementById('dados_usuario');
//    
//        if(post == true){
//            dadosPessoais.className = 'nav-item';
//            dadosUsuario.className = 'nav-item active';
////            divDadosPessoais.className = 'tab-pane';
//            divDadosUsuario.className = 'tab-pane active';
//        }
//    }


   $(document).ready(function () {
        $('#cpf_participante').mask('999.999.999-99');
        $('#telefone_participante').mask('(99) 99999-9999');
        
        $('#form_participante').validate({
            // Define as regras
            rules: {
                nome_participante: {
                    required: true,
                },
                cpf_participante: {
                    required: true,
                    minlength: 14,
                },
                email_participante: {
                    required: true,
                    email: true,
                },

            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_participante: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_participante: {
                    required: "Campo CPF não pode ser vazio!",
                    minlength: "O Campo CPF deve ter 11 números!"
                    
                },
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
            }
        });
    });
</script>



    