<div class="box-header with-border">
    <h3 class="box-title">Editar participante</h3>
</div>
<?php
if (isset($_POST['botao_salvar']) && ($this->retorno == true)) {
    ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><b>Parabens!</b></h4>
                </div>
                <div class="modal-body">

                    <b>Participante alterado com sucesso!</b><br /><br />
                    Você deseja fazer mais alguma alteração?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Sim</button>
                    <a href="/participante" class="btn btn-primary">Não</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } else if (isset($_POST['botao_salvar']) && ($this->retorno == false)) { ?>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content ">
                <div class="modal-header " >
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel" ><b>Atenção!</b></h4>
                </div>
                <div class="modal-body">
                    Verificar:
                    <ul>
                        <li class="list-inline">CPF já cadastrado</li>
                        <li class="list-inline">E-mail já cadastrado </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>

                </div>
            </div>
        </div>
    </div>
    <script>$("#myModal").modal();</script>
<?php } ?>



<hr />
<div class="content">
    <?php
    $formParticipante = $this->form_participante;
    $formParticipante->prepare();
    ?>
    <?= $this->form()->openTag($formParticipante) ?>

    <div class="form-group">
        <?= $this->formRow($formParticipante->get('nome_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('cpf_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('telefone_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('email_participante')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($formParticipante->get('cod_tipo_participante')); ?>
    </div>
    <div class="form-group">
        <button type="submit" name="botao_salvar" id="botao_salvar" class="btn btn-primary" ><span class="glyphicon glyphicon-floppy-save"></span> Salvar</button>
        <a href="<?= $this->url('participante') ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
    </div>
    <?= $this->form()->closeTag() ?>
</div>

<script>

    $(document).ready(function () {
        $('#cpf_participante').mask('999.999.999-99');
        $('#telefone_participante').mask('(99) 99999-9999');

        $('#form_participante').validate({
            // Define as regras
            rules: {
                nome_participante: {
                    required: true,
                },
                cpf_participante: {
                    required: true,
                    minlength: 14,
                },
                email_participante: {
                    required: true,
                    email: true,
                },
                tipo_participante: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_participante: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_participante: {
                    required: "Campo CPF não pode ser vazio!",
                    minlength: "O Campo CPF deve ter 11 números!"

                },
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                tipo_participante: {
                    required: "Campo Tipo de Participante não pode ser vazio!",
                },
            }
        });
    });
</script>