<div class="box-header with-border">
	<h3 class="box-title">Editar participante</h3>
</div>
<hr />
      <div class="content">
<?php
$formParticipante = $this->form_participante;
$formParticipante->setAttribute('action',$this->url('participante-editar',array('action'=>'editar','cod_participante'=>$formParticipante->get('cod_participante')->getValue())));
$formParticipante->prepare();
?>
<?=$this->form()->openTag($formParticipante)?>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('cod_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('nome_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('cpf_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('telefone_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('email_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('cod_tipo_participante')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($formParticipante->get('botao_salvar')); ?>
            <a href="<?=$this->url('participante') ?>" class="btn btn-danger" >Cancelar</a>
        </div>
<?=$this->form()->closeTag()?>
 </div>

<script>

   $(document).ready(function () {
        $('#cpf_participante').mask('999.999.999-99');
        $('#telefone_participante').mask('(99) 99999-9999');
        
        $('#form_participante').validate({
            // Define as regras
            rules: {
                nome_participante: {
                    required: true,
                },
                cpf_participante: {
                    required: true,
                },
                email_participante: {
                    required: true,
                    email: true,
                },
                tipo_participante: {
                    required: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                nome_participante: {
                    required: "Campo Nome não pode ser vazio!",
                },
                cpf_participante: {
                    required: "Campo CPF não pode ser vazio!",
                    //minlength: "O Campo CPF deve ter 11 números!"
                    
                },
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
                tipo_participante: {
                    required: "Campo Tipo de Participante não pode ser vazio!",
                },
            }
        });
    });
</script>