<h2><?=$this->escapeHtml($this->title) ?></h2>
<hr>
<a href="<?=$this->urlCadastrar ?>" class="btn btn-success">Novo Cadastro</a>
<p></p>
<table id="data_table" class="table table-hover table-bordered dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Telefone</th>
                        <th>E-mail</th>
                        <th>Tipo Participante</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
<?=$this->partialLoop('partial_loop_listar.phtml', $this->paginator) ?>  
                </tbody>
</table>
<p>
    <?=$this->paginationControl($this->paginator,
                                        'Sliding',
                                        'pagination',array('route'=>'participante')); ?>
</p>
