<tr>
    <td><?= $this->escapeHtml($this->codParticipante) ?></td>
    <td><?= $this->escapeHtml($this->nomeParticipante) ?></td>
    <!--<td><?//$this->MascaraCpf()->formatarCpf($this->cpfParticipante)?></td>-->
    <td><?= $this->cpfParticipante ?></td>
    <td><?= $this->telefoneParticipante ?></td>
    <td><?= $this->escapeHtml($this->emailParticipante) ?></td>
    <td><?= $this->tipoParticipante ?></td>
    <td>
        <a href="<?php echo $this->url('participante-editar', array('action' => 'editar', 'cod_participante' => $this->codParticipante)) ?>" class="btn btn-primary " ><span class="glyphicon glyphicon-pencil"></span>&nbsp;Editar</a>
        <a href="<?php echo $this->url('participante-excluir', array('action' => 'excluir', 'cod_participante' => $this->codParticipante)) ?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span>&nbsp;Excluir</a>
    </td>

</tr>
<script>
//
//    function marcarParticipante(cod_participante) {
//        var codParticipante = cod_participante.value;
//
//        var editar = document.getElementById('editar-btn');
//        var excluir = document.getElementById('excluir-btn');
////        var porprojeto = document.getElementById('porprojeto-btn');
//
//        editar.removeAttribute('disabled');
//        excluir.removeAttribute('disabled');
////        porprojeto.removeAttribute('disabled');
//
//        editar.setAttribute('href', 'participante-editar/' + codParticipante);
//        excluir.setAttribute('href', 'participante-excluir/' + codParticipante);
////        porprojeto.setAttribute('href', 'participanteprojeto/' + codParticipante);
//
//    }

</script>