<tr>
    <td><?=$this->escapeHtml($this->codParticipante)?></td>
    <td><?=$this->escapeHtml($this->nomeParticipante)?></td>
    <td><?=$this->MascaraCpf()->formatarCpf($this->cpfParticipante)?></td>
    <td><?=$this->telefoneParticipante?></td>
    <td><?=$this->escapeHtml($this->emailParticipante)?></td>
    <td><?=$this->tipoParticipante?></td>
    <td>
        <a href="<?php echo $this->url('participante-editar',array('action' => 'editar', 'cod_participante' => $this->codParticipante))?>" class="btn btn-info" >Editar</a>
        <a href="<?php echo $this->url('participante-excluir',array('action' => 'excluir', 'cod_participante' => $this->codParticipante))?>" class="btn btn-danger">Excluir</a>
    </td>    
</tr>