<div class="box-header with-border">
    <h3 class="box-title">Recuperar senha</h3>
</div>
<hr />

<div class="tab-content">
    <?php $this->Notificacoes(); ?>
    <?php
    $formParticipante = $this->form_participante;
    $formParticipante->prepare();
    echo $this->form()->openTag($formParticipante);
    ?>

    <div class="form-group">
        <?= $this->formRow($formParticipante->get('email_participante')); ?> 
    </div>

    <div class="form-group">
        <div>
            <button type="submit" name="botao_enviar" id="botao_enviar" class="btn btn-primary" ><span class="glyphicon glyphicon-send"></span> Enviar</button>
            <a href="<?= $this->url('login') ?>" class="btn btn-warning" ><span class="glyphicon glyphicon-backward"></span> Voltar</a>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>

</div>

<script>

    $(document).ready(function () {

        $('#form_participante').validate({
            // Define as regras
            rules: {
                email_participante: {
                    required: true,
                    email: true,
                },
            },
            // Define as mensagens de erro para cada regra
            messages: {
                email_participante: {
                    required: "Campo E-mail não pode ser vazio!",
                    email: "Formato email dever ter (@ e .com)!",
                },
            }
        });
    });
</script>