<h1>Página inicial logado</h1>
<p>Bem vindo! <?= $this->nome_participante ?>!</p>

<p>Em qual projeto você pretente trabalhar? 
    <select name="projetos" id="projetos" onchange="escolherProjeto(this);">
        <option>Selecione...</option>
        <?= $this->partialLoop('partial_loop_projetos.phtml', $this->partial_loop_projetos) ?>  
    </select>
</p>

<script>
    function escolherProjeto(proj){
       alert(proj.value);
    }
    
//function escolherProjeto(){
//       var ajax = new XMLHttpRequest();
//       ajax.onreadystatechange = function () {
//       if (ajax.readyState == 4)
//       {
//           if (ajax.status == 200) {
//               if (ajax.responseText) {
//             //alert(ajax.responseText);
//                       document.getElementById('t53_garant').value = ajax.responseText;
//               }
//                   else{
//               alert("error");
//                    }
//
//           } else {
//              // alert(ajax.statusText);
//           }
//       }
//   }
//       dados = 'method=carregaGarantia&t53_codbem='+t53_codbem;
////alert(dados);
//       ajax.open("POST", "lt_lote_empenhoRCP.php", true);
//       ajax.setRequestHeader('Content-Type','application/x-www-form-urlencoded;charset=iso-8859-1');
//       ajax.send(dados);
//   }
</script>